# Generated by Django 6.0.2 on 2026-03-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_suscripcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Gratis'), ('MONTHLY', 'Mensual'), ('ANNUAL', 'Anual')], default='FREE', max_length=10),
        ),
    ]
