# Generated by Django 6.0.2 on 2026-03-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_fecha_suscripcion_usuario_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('USER', 'Usuario Estándar')], default='USER', max_length=10),
        ),
    ]
