# Generated by Django 6.0.2 on 2026-03-01 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.ImageField(upload_to='comprobantes/')),
                ('plan_solicitado', models.CharField(choices=[('MONTHLY', 'Mensual'), ('ANNUAL', 'Anual')], max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_pago', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
